apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-influxdb
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: influxdb
    spec:
      containers:
      - image: influxdb
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        name: influxdb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /root/.influxdb/
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim